### ISSUE TITLE
Error in interface and test

### ISSUE THREAD

**Issue by aanexplus** [sachinkariyattin/HWCR#1]
There is an issue with interface.m and test.m... Geomtric future extraction doesnt work. Please fix

**Comment by sachinkariyattin** [comment]
Please use Matlab 2013 or above

**Comment by aanexplus** [comment]
I am using matlab 2015. That's what is confusing me.
On Aug 30, 2015 8:22 AM, sachinkariyattin notifications@github.com wrote:Please use Matlab 2013 or above
