### ISSUE TITLE
Issues in the geo_train.m and not letting the output

### ISSUE THREAD

**Issue by lavanyalathakonjeti** [sachinkariyattin/HWCR#2]
[errors_in geo_train.docx](https://github.com/sachinkariyattin/HWCR/files/434212/errors_in.geo_train.docx)

**Comment by sachinkariyattin** [comment]
Make sure you have changed the default paths in the source code depending on your system (i.e change  the path according to your workspace). Also, use Matlab 2013 or above versions while running this code.

**Comment by lavanyalathakonjeti** [comment]
It worked ..Thanks :)

**Comment by RahulBansal1** [comment]
lavanyalathakonjeti, If you encounter the following type of error then please help me resolve this error.
??? Undefined function or method 'rng' for input arguments of type 'char'.

Error in ==> train at 10
rng('default');

Error in ==> interface>pushbutton13_Callback at 359
        train

Error in ==> gui_mainfcn at 96
        feval(varargin{:});

Error in ==> interface at 44
    gui_mainfcn(gui_State, varargin{:});

Error in ==> @(hObject,eventdata)interface('pushbutton13_Callback',hObject,eventdata,guidata(hObject))

 
??? Error while evaluating uicontrol Callback

??? Undefined function or method 'rng' for input arguments of type 'char'.

Error in ==> geo_train at 10
rng('default');

Error in ==> interface>pushbutton13_Callback at 363
        geo_train

Error in ==> gui_mainfcn at 96
        feval(varargin{:});

Error in ==> interface at 44
    gui_mainfcn(gui_State, varargin{:});

Error in ==> @(hObject,eventdata)interface('pushbutton13_Callback',hObject,eventdata,guidata(hObject))
