### ISSUE TITLE
Error after training

### ISSUE THREAD

**Issue by mizuQnie** [sachinkariyattin/HWCR#4]
after training
Undefined function 'feature_extractor' for input arguments of type 'logical'.

Error in interface>pushbutton11_Callback (line 193)
        z=feature_extractor(z);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in interface (line 44)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)interface('pushbutton11_Callback',hObject,eventdata,guidata(hObject))

Error while evaluating uicontrol Callback

**Comment by RahulBansal1** [comment]
mizuQnie, whether your errors are solved or not. If you solved the errors, please help me because I encounter the same type of errors.

**Comment by mizuQnie** [comment]
I was not able to solve the errors. Sorry.
