### ISSUE TITLE
Very low accuracy rate

### ISSUE THREAD

**Issue by Arka161** [sachinkariyattin/HWCR#6]
Both of the Algorithms execute successfully after updating the given directory in the source code. 
However, the Accuracy rate is roughly 40% when tried actual handwritten data-sets. The Geometric Algorithm is more accurate of the two.

# Possible Fix: 

Increasing the amount of data the Neural Network is trained with. Right now, the ANN is supplied with roughly 25 images of every letter. The ANNs accuracy will be amplified with the data-set is increased. 

# Program Improvements: 

The program can be improved with support for digits, thus reading handwritten e-mail IDs, phone numbers with ease.

**Comment by RahulBansal1** [comment]
Can you please make me clear how the input108.mat works and from where the data is taken for features and how the features are put in that input108.mat and what exactly does the target650.mat works.Please let me clear how they are working and how the input is taken.

**Comment by iamManishpk** [comment]
sir please help me out how to use your downloaded files

**Comment by iamManishpk** [comment]
i am presenting OCR as aproject

**Comment by iamManishpk** [comment]
please reply asap
